name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - assets/*
      - gui/*
      - scripts/*
      - LICENSE
      - NOTICES
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - assets/*
      - gui/*
      - scripts/*
      - LICENSE
      - NOTICES
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Create .condarc file
      run: |
        echo 'create_default_packages: []' > .condarc

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        activate-environment: mp3-autotagger
        auto-activate-base: false
        condarc-file: .condarc

    - name: Install dependencies with conda and pip
      shell: bash -l {0}
      run: |
        conda install ffmpeg
        python -m pip install --upgrade pip
        pip install .
        pip install pyinstaller

    - name: Build binary
      shell: bash -l {0}
      run: |
        pyinstaller mp3_autotagger.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary-${{ matrix.os }}
        path: dist/

    - name: Run integration tests (Linux & macOS)
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
      run: |
        . ./scripts/integration_test_linux_macos.sh

    - name: Run integration tests (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        .\scripts\integration_test_win.ps1
