name: Build binaries and link to release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build Binary
      run: pyinstaller mp3_autotagger.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary-${{ matrix.os }}
        path: dist/
