name: unit tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - assets/*
      - gui/*
      - scripts/*
      - LICENSE
      - NOTICES.md
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - assets/*
      - gui/*
      - scripts/*
      - LICENSE
      - NOTICES.md
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Create .condarc file
      run: |
        echo 'create_default_packages: []' > .condarc

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.10"
        activate-environment: mp3-autotagger
        auto-activate-base: false
        condarc-file: .condarc
        channels: conda-forge,defaults
        channel-priority: strict

    - name: Update Conda
      shell: bash -l {0}
      run: conda update -n base -c defaults conda -y

    - name: Install dependencies with conda and pip
      shell: bash -l {0}
      run: |
        conda install ffmpeg
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run formatters
      shell: bash -l {0}
      run: |
        flake8 .
        black --check .
        isort --check-only .

    - name: Run unit tests
      shell: bash -l {0}
      run: |
        pytest
