name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10.12"
        activate-environment: mp3-autotagger
        auto-activate-base: false

    - name: Install dependencies with conda and pip
      shell: bash -l {0}
      run: |
        conda install ffmpeg
        python -m pip install --upgrade pip
        pip install -e .[dev,test,tools]

    - name: Run unit tests
      shell: bash -l {0}
      run: |
        pytest

    - name: Run formatters
      shell: bash -l {0}
      run: |
        flake8 .
        black --check .
        isort --check-only .
